language: python
python:
    - "2.7"

install:
    - python -c "$(curl -fsSL https://raw.githubusercontent.com/platformio/platformio/master/scripts/get-platformio.py)"

script:
    - platformio ci HC-05/MASTER_SLAVE/Slave/src --board=uno --board=nanoatmega328 --board=megaatmega2560 --board=esp32dev
    - platformio ci HC-05/MASTER_SLAVE/Master/src --board=uno --board=nanoatmega328 --board=megaatmega2560 --board=esp32dev
    - platformio ci Serial_Communication_Processing_Mega/megaatmega2560/src  --board=megaatmega2560 
    
notifications:
  email:
    on_success: change
    on_failure: change
