language: python
python:
    - "2.7"

install:
    - python -c "$(curl -fsSL https://raw.githubusercontent.com/platformio/platformio/master/scripts/get-platformio.py)"

script:
    - platformio ci HC-05/MASTER_SLAVE/Slave/src --board=uno --board=nanoatmega328 --board=megaatmega2560 --board=esp32dev
    - platformio ci HC-05/MASTER_SLAVE/Master/src --board=uno --board=nanoatmega328 --board=megaatmega2560 --board=esp32dev
    - platformio ci Serial_Communication_Processing_Mega/megaatmega2560/src  --board=megaatmega2560 
    
notifications:
  email:
    on_success: change
    on_failure: change

language: c

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.6.5-linux64.tar.xz
  - tar xf arduino-1.6.5-linux64.tar.xz
  - sudo mv arduino-1.6.5 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
  
  script:
  - arduino --verify --board ${BOARD} $GridEye/GridEye.ino
  
notifications:
  email:
    on_success: change
    on_failure: change
    
env:
 - BOARD=arduino:avr:uno
# - BOARD=arduino:avr:yun
# - BOARD=arduino:avr:diecimila:cpu=atmega168
# - BOARD=arduino:avr:diecimila:cpu=atmega328
# - BOARD=arduino:avr:nano:cpu=atmega168
 - BOARD=arduino:avr:nano:cpu=atmega328
# - BOARD=arduino:avr:mega:cpu=atmega1280
# - BOARD=arduino:avr:mega:cpu=atmega2560
# - BOARD=arduino:avr:megaADK
# - BOARD=arduino:avr:leonardo
# - BOARD=arduino:avr:micro
# - BOARD=arduino:avr:esplora
# - BOARD=arduino:avr:mini:cpu=atmega168
# - BOARD=arduino:avr:mini:cpu=atmega328
# - BOARD=arduino:avr:ethernet
# - BOARD=arduino:avr:bt:cpu=atmega168
# - BOARD=arduino:avr:bt:cpu=atmega328
# - BOARD=arduino:avr:lilypad:cpu=atmega168
# - BOARD=arduino:avr:lilypad:cpu=atmega328
# - BOARD=arduino:avr:pro:cpu=atmega168
# - BOARD=arduino:avr:pro:cpu=atmega328
# - BOARD=arduino:sam:arduino_due_x
