language: python
python:
    - "2.7"

env:
    - PLATFORMIO_CI_SRC=HC-05/MASTER_SLAVE/MASTER/MASTER.ino
  
install:
    - pip install -U platformio

script:
    - platformio ci --lib="." --board=uno --board=nano --board=mega $PLATFORMIO_CI_EXTRA_ARGS
