language: python
python:
    - "2.7"

install:
    - python -c "$(curl -fsSL https://raw.githubusercontent.com/platformio/platformio/master/scripts/get-platformio.py)"

script:
    - platformio ci HC-05/MASTER_SLAVE/Slave/src --board=uno --board=nano --board=mega --board=ESP32
    
notifications:
  email:
    on_success: change
    on_failure: change
